### ISSUE TITLE
print_port_def

### ISSUE THREAD

**Issue by fyrer** [ismelykh/gst-omx-deinterlace#1]
Hi! I'm trying to test your fork. But after the build hav a problem:

[root@raspb ~]# gst-inspect-1.0 omxh264dec
(gst-plugin-scanner:30102): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstomx.so': /usr/lib/gstreamer-1.0/libgstomx.so: undefined symbol: print_port_def
No such element or plugin 'omxh264dec'

**Comment by ismelykh** [comment]
Hi, thanks, just pushed the fix.

**Comment by fyrer** [comment]
Thanks!
Now i hav new problem. 
It's works with the stream?

My pipeline:
gst-launch-1.0 -vvvv --gst-debug-level=3 souphttpsrc is-live=true location=http://192.168.1.2:8080/ch5 ! queue  ! tsdemux  name=dmx ! queue ! h264parse ! omxh264dec  ! omxh264enc target-bitrate=5500000 control-rate=1 ! video/x-h264,stream-format=byte-stream,profile=high ! queue ! mpegtsmux name=mux ! queue ! tcpserversink port=5000 host=192.168.1.4 

DEBUG:

/GstPipeline:pipeline0/GstH264Parse:h264parse0.GstPad:src: caps = "video/x-h264\,\ stream-format\=(string)byte-stream\,\ alignment\=(string)au\,\ width\=(int)1920\,\ height\=(int)1080\,\ framerate\=(fraction)25/1\,\ parsed\=(boolean)true\,\ pixel-aspect-ratio\=(fraction)1/1\,\ level\=(string)4\,\ profile\=(string)high"
/GstPipeline:pipeline0/GstOMXH264Dec-omxh264dec:omxh264dec-omxh264dec0.GstPad:sink: caps = "video/x-h264\,\ stream-format\=(string)byte-stream\,\ alignment\=(string)au\,\ width\=(int)1920\,\ height\=(int)1080\,\ framerate\=(fraction)25/1\,\ parsed\=(boolean)true\,\ pixel-aspect-ratio\=(fraction)1/1\,\ level\=(string)4\,\ profile\=(string)high"
/GstPipeline:pipeline0/GstOMXH264Dec-omxh264dec:omxh264dec-omxh264dec0.GstPad:src: caps = "video/x-raw(memory:EGLImage)\,\ format\=(string)RGBA\,\ width\=(int)1920\,\ height\=(int)1080\,\ pixel-aspect-ratio\=(fraction)1/1\,\ interlace-mode\=(string)progressive\,\ colorimetry\=(string)1:1:0:0\,\ framerate\=(fraction)25/1"
0:00:02.473966801 20074   0xb20800 WARN                GST_PADS gstpad.c:3739:gst_pad_peer_query:omxh264dec-omxh264dec0:src could not send sticky events
0:00:02.474405029 20074   0xb20800 WARN            videodecoder gstvideodecoder.c:3352:gst_video_decoder_negotiate_pool:<omxh264dec-omxh264dec0> Subclass failed to decide allocation
/GstPipeline:pipeline0/GstOMXH264Dec-omxh264dec:omxh264dec-omxh264dec0.GstPad:src: caps = "video/x-raw\,\ format\=(string)RGBA\,\ width\=(int)1920\,\ height\=(int)1080\,\ pixel-aspect-ratio\=(fraction)1/1\,\ interlace-mode\=(string)progressive\,\ colorimetry\=(string)1:1:0:0\,\ framerate\=(fraction)25/1"
0:00:02.479015688 20074   0xb20800 WARN                GST_PADS gstpad.c:3739:gst_pad_peer_query:omxh264dec-omxh264dec0:src could not send sticky events
/GstPipeline:pipeline0/GstOMXH264Dec-omxh264dec:omxh264dec-omxh264dec0.GstPad:src: caps = "video/x-raw\,\ format\=(string)I420\,\ width\=(int)1920\,\ height\=(int)1080\,\ pixel-aspect-ratio\=(fraction)1/1\,\ interlace-mode\=(string)progressive\,\ colorimetry\=(string)bt709\,\ framerate\=(fraction)25/1"
/GstPipeline:pipeline0/GstOMXH264Enc-omxh264enc:omxh264enc-omxh264enc0.GstPad:sink: caps = "video/x-raw\,\ format\=(string)I420\,\ width\=(int)1920\,\ height\=(int)1080\,\ pixel-aspect-ratio\=(fraction)1/1\,\ interlace-mode\=(string)progressive\,\ colorimetry\=(string)bt709\,\ framerate\=(fraction)25/1"

**Comment by ismelykh** [comment]
I just realised that in case of dec->enc scheme not tunelled mode used, this port was for tunneled mode which used in case of rendering, so it needs some additional work for adding deinterlacer in case of non-rendering scheme, like you use.

**Comment by fyrer** [comment]
Streaming work with original gst-omx(1.2 and git too)
Now I tried play file:
gst-launch-1.0 -vvvv --gst-debug-level=3 filesrc location=/root/test.ts ! typefind ! tsdemux ! queue ! h264parse ! omxh264dec ! aasink 

Problems the same, pipe freeze and memory leak

**Comment by ismelykh** [comment]
This port was implemented and tested only for  ... ! omxh264dec ! glimagesink pipeline.

**Comment by fyrer** [comment]
Thank! Will try after xorg installation. 
Do you have a plan to implement for else sink?

**Comment by ismelykh** [comment]
glimagesink works without X, it uses EGL if there is no X.
I don't have any plans for implementation non egl rendering, as its the only zerocopy way for rendering on rpi and gstreamer.
Possibly will add support when will have free time.
